language: python
python:
- "3.7"

env:
- DJANGO_VERSION=2.0.13

#install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py collectstatic
- python manage.py test
- python manage.py events/features
